services:
  php:
    container_name: '${APP_NAME}'
    image: php:8.0.11
    command: sh -c 'cd /app && php -S 0.0.0.0:8000'
    ports:
      - "80:8000"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: mariadb:10.6
    container_name: '${APP_NAME}-db'
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./mysql_data:/var/lib/mysql